services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
      - ./public:/app/public:ro

