services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberfolio
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /opt/portfolio/config:/app/config:ro
      - ./app/public:/app/public:ro

