services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberfolio
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./public:/app/public:ro
      - ./private:/app/private:ro

